CREATE TABLE income (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    amount BIGINT
);

CREATE TABLE expense (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    amount BIGINT
);

CREATE TABLE budget (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    amount BIGINT
);
